name: Update PowerShell Script

on:
    schedule:
        - cron: "0 0 * * *" # This runs the workflow daily at midnight
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
    update-script:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Update PowerShell Script
              shell: pwsh
              run: |
                  $GitHubUrl = "https://raw.githubusercontent.com/itpro-tips/PowerShell-Toolbox/master/Update-AllPowerShellModules.ps1"
                  Get-ChildItem
                  $LocalFilePath = "src\public\Update-AllPowershellModules.ps1"
                  Invoke-WebRequest -Uri $GitHubUrl -OutFile $LocalFilePath

            - name: Check for changes
              id: changes
              shell: pwsh
              run: |
                  git diff --quiet
                  if ($LASTEXITCODE -ne 0) {
                      Write-Output "Changes detected"
                      echo "changes_detected=true" >> $env:GITHUB_ENV
                  } else {
                      Write-Output "No changes detected"
                      exit 0
                  }

            - name: Commit and push changes
              if: env.changes_detected == 'true'
              shell: pwsh
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add .
                  git commit -m "Update PowerShell script"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
